config/routes.rb
Rails.application.routes.draw do
  # scope ':account_id' do
  #   resource :account, path: '', only: [] do
  #     resources :projects, path: ''
  #   end
  # end
  # resource :account, path: ''

  resources :accounts, path: String.new
  resources :accounts, only: [], path: String.new do
    resources :projects, except: [:index], path: String.new
  end

  root to: 'accounts#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :projects

  validates :name, presence: true

  before_save { self.slug = name.parameterize }
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :account

  validates :name, presence: true

  before_save { self.slug = name.parameterize }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to @account
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to @account
    else
      render :edit
    end
  end

  def destroy
    @account.destroy!
    redirect_to root_path
  end

private

  def account_params
    params.require(:account).permit(:name)
  end

  def set_account
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_account

  def current_account
    @account ||= Account.find(params[:account_id])
  end
  alias_method :set_current_account, :current_account
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def show
    @project = current_account.projects.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_account.projects.build(project_params)
    if @project.save
      redirect_to [current_account, @project]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to [current_account, @project]
    else
      render :edit
    end
  end

  def destroy
    @project.destroy!
    redirect_to current_account
  end

private

  def project_params
    params.require(:project).permit(:name)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for object do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit <%= @account.name %></h1>

<%= render 'form', object: @account %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<ul>
  <% @accounts.each do |account| %>
    <li><%= link_to account.name, account %></li>
  <% end %>
</ul>

<%= link_to "New Account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', object: @account %>

app/views/accounts/show.html.erb
<h1>Account: <%= @account.name %></h1>

<h3>Projects</h3>

<ul>
  <% @account.projects.each do |project| %>
    <li><%= link_to project.name, [@account, project] %></li>
  <% end %>
</ul>

<ul>
  <li><%= link_to "Edit", [:edit, @account] %></li>
  <li><%= link_to "Delete", @account, method: :delete %></li>
</ul>

<%= link_to "New Project", [:new, @account, :project] %>
<%= link_to "Back to Accounts", accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubRoutes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Account: <%= link_to current_account.name, current_account %></h1>

<h3>NEW PROJECT</h3>

<%= render 'form', object: [current_account, @project] %>

app/views/projects/new.html.erb
<h1>Account: <%= link_to current_account.name, current_account %></h1>

<h3>NEW PROJECT</h3>

<%= render 'form', object: [current_account, @project] %>

app/views/projects/show.html.erb
<h1>Account: <%= link_to current_account.name, current_account %></h1>
<h3>Project: <%= link_to @project.name, [current_account, @project] %></h1>

<%= link_to "Edit", [:edit, current_account, @project] %>
<%= link_to "Delete", [current_account, @project], method: :delete %>